import { IWebsiteConfiguration } from '../../models/configuration/IWebsiteConfiguration'

const websiteConfiguration: IWebsiteConfiguration = {
  allowCookiesStorageKey: 'allow_cookies',
  bugReportUrl: 'https://discord.gg/bugreport',
  buildsFilterStorageKey: 'builds_filter',
  buildSharingUrl: 's/',
  buildsPageStorageKey: 'builds_page',
  buildsSortFieldStorageKey: 'builds_sort_field',
  buildsSortOrderStorageKey: 'builds_sort_order',
  buildStorageKeyPrefix: 'build_',
  cacheDuration: 3600,
  contactAddress: 'contact@address.com',
  discordUrl: 'https://discord.gg/server',
  endpointChangelog: 'data/changelog.json',
  endpointItems: 'data/items.json',
  endpointPresets: 'data/presets.json',
  endpointPrices: 'data/prices.json',
  endpointTarkovValues: 'data/tarkov-values.json',
  endpointWebsiteConfiguration: 'data/website-configuration.json',
  exportFileExtension: '.ttb',
  exportFileNamePrefix: 'TotovBuilder',
  exportWarningShowedStorageKey: 'export_warning',
  fetchMaxTries: 3,
  fetchTimeout: 30,
  fetchWaitTimeBetweenRetries: 2,
  githubUrl: 'https://github.com/User/Reposiory',
  globalFilterStorageKey: 'global_filter',
  itemsFilterAndSortCategoryStorageKey: 'items_sort_category',
  itemsFilterStorageKey: 'items_filter',
  itemsSortFieldStorageKey: 'items_sort_field',
  itemsSortOrderStorageKey: 'items_sort_order',
  languageStorageKey: 'language',
  notificationErrorDuration: 10,
  notificationInformationDuration: 5,
  notificationSuccessDuration: 5,
  notificationWarningDuration: 10,
  postUpdatePeriod: false,
  version: '1.6.0',
  versionStorageKey: 'version'
}

export default websiteConfiguration