import { IWebsiteConfiguration } from '../../models/configuration/IWebsiteConfiguration'

const websiteConfiguration: IWebsiteConfiguration = {
  allowCookiesStorageKey: 'allow_cookies',
  bugReportUrl: 'https://discord.gg/bugreport',
  buildsFilterStorageKey: 'builds_filter',
  buildSharingUrl: 's/',
  buildsPageStorageKey: 'builds_page',
  buildsSortOrderStorageKey: 'builds_sort_order',
  buildsSortPropertyStorageKey: 'builds_sort_field',
  buildStorageKeyPrefix: 'build_',
  cacheDuration: 3600,
  contactAddress: 'contact@address.com',
  discordUrl: 'https://discord.gg/server',
  endpointChangelog: 'data/changelog.json',
  endpointItems: 'data/items_{0}.json',
  endpointPresets: 'data/presets.json',
  endpointPrices: 'data/prices_{0}_{1}.json',
  endpointTarkovValues: 'data/tarkov-values.json',
  endpointUrlShortener: 'https://spoo.me/',
  endpointWebsiteConfiguration: 'data/website-configuration.json',
  exportFileExtension: '.ttb',
  exportFileNamePrefix: 'TotovBuilder',
  exportWarningShowedStorageKey: 'export_warning_showed',
  exportWarningStorageKey: 'export_warning',
  fetchMaxTries: 3,
  fetchTimeout: 30,
  fetchWaitTimeBetweenRetries: 2,
  gameModes: [
    'pvp',
    'pve'
  ],
  gameModeStorageKey: 'gameMode',
  githubUrl: 'https://github.com/User/Reposiory',
  globalFilterStorageKey: 'global_filter',
  itemCategorySortOrderStorageKeySuffix: '_sort_order',
  itemCategorySortPropertyStorageKeySuffix: '_sort_field',
  itemsFilterAndSortCategoryStorageKey: 'items_sort_category',
  itemsFilterStorageKey: 'items_filter',
  itemsLanguageStorageKey: 'items_language',
  itemsLanguages: [
    'en',
    'fr',
    'cs',
    'de',
    'es',
    'hu',
    'it',
    'ja',
    'ko',
    'pl',
    'pt',
    'ro',
    'ru',
    'sk',
    'tr',
    'zh'
  ],
  itemsSortOrderStorageKey: 'items_sort_order',
  itemsSortPropertyStorageKey: 'items_sort_field',
  languageStorageKey: 'language',
  notificationErrorDuration: 10,
  notificationInformationDuration: 5,
  notificationSuccessDuration: 5,
  notificationWarningDuration: 10,
  outdatedSharableUrlWarningStorageKey: 'outdated_sharable_url_warning',
  postUpdatePeriod: false,
  version: '1.6.0',
  versionStorageKey: 'version'
}

export default websiteConfiguration