<template>
  <ItemOptionHeader
    v-model:sortingData="updatableSortingData"
    v-model:filter="updatableFilter"
  >
    <AmmunitionOptionHeader
      v-if="itemPropertiesService.isAmmunition(categoryId)"
      v-model="updatableSortingData"
    />
    <ArmorModOptionHeader
      v-else-if="itemPropertiesService.isArmorMod(categoryId)"
      v-model="updatableSortingData"
    />
    <ArmorOptionHeader
      v-else-if="itemPropertiesService.isArmor(categoryId)"
      v-model="updatableSortingData"
    />
    <BackpackOptionHeader
      v-else-if="itemPropertiesService.isBackpack(categoryId)"
      v-model="updatableSortingData"
    />
    <ContainerOptionHeader
      v-else-if="itemPropertiesService.isContainer(categoryId)"
      v-model="updatableSortingData"
    />
    <EyewearOptionHeader
      v-else-if="itemPropertiesService.isEyewear(categoryId)"
      v-model="updatableSortingData"
    />
    <GrenadeOptionHeader
      v-else-if="itemPropertiesService.isGrenade(categoryId)"
      v-model="updatableSortingData"
    />
    <HeadwearOptionHeader
      v-else-if="itemPropertiesService.isHeadwear(categoryId)"
      v-model="updatableSortingData"
    />
    <MagazineOptionHeader
      v-else-if="itemPropertiesService.isMagazine(categoryId)"
      v-model="updatableSortingData"
    />
    <MeleeWeaponOptionHeader
      v-else-if="itemPropertiesService.isMeleeWeapon(categoryId)"
      v-model="updatableSortingData"
    />
    <ModOptionHeader
      v-else-if="itemPropertiesService.isMod(categoryId)"
      v-model="updatableSortingData"
    />
    <RangedWeaponModOptionHeader
      v-else-if="itemPropertiesService.isRangedWeaponMod(categoryId)"
      v-model="updatableSortingData"
    />
    <RangedWeaponOptionHeader
      v-else-if="itemPropertiesService.isRangedWeapon(categoryId)"
      v-model="updatableSortingData"
    />
    <VestOptionHeader
      v-else-if="itemPropertiesService.isVest(categoryId)"
      v-model="updatableSortingData"
    />
  </ItemOptionHeader>
</template>

<script lang="ts" src="./OptionHeaderSelectorComponent.ts" />
<style scoped lang="css" src="./OptionHeaderSelectorComponent.css" />