<template>
  <SelectedItemSummary
    v-if="modelValue != null && item != null"
    v-model="modelValue"
    :can-be-looted="canBeLooted"
    :preset="preset"
  >
    <AmmunitionSummary
      v-if="itemPropertiesService.isAmmunition(item)"
      :item="item"
      :show-empty-entries="false"
    />
    <ArmorSummary
      v-else-if="itemPropertiesService.isArmor(item)"
      :item="item"
      :show-empty-entries="false"
    />
    <ArmorModSummary
      v-else-if="itemPropertiesService.isArmorMod(item)"
      :item="item"
      :show-empty-entries="false"
    />
    <ContainerSummary
      v-else-if="itemPropertiesService.isContainer(item)"
      :item="item"
    />
    <EyewearSummary
      v-else-if="itemPropertiesService.isEyewear(item)"
      :item="item"
      :show-empty-entries="false"
    />
    <GrenadeSummary
      v-else-if="itemPropertiesService.isGrenade(item)"
      :item="item"
      :show-empty-entries="false"
    />
    <HeadwearSummary
      v-else-if="itemPropertiesService.isHeadwear(item)"
      :item="item"
      :show-empty-entries="false"
    />
    <MagazineSummary
      v-else-if="itemPropertiesService.isMagazine(item)"
      :item="item"
      :show-empty-entries="false"
    />
    <MeleeWeaponSummary
      v-else-if="itemPropertiesService.isMeleeWeapon(item)"
      :item="item"
    />
    <ModSummary
      v-else-if="itemPropertiesService.isMod(item)"
      :item="item"
      :show-empty-entries="false"
    />
    <RangedWeaponSummary
      v-else-if="itemPropertiesService.isRangedWeapon(item)"
      :item="item"
    />
    <RangedWeaponModSummary
      v-else-if="itemPropertiesService.isRangedWeaponMod(item)"
      :item="item"
      :show-empty-entries="false"
    />
    <VestSummary
      v-else-if="itemPropertiesService.isVest(item)"
      :item="item"
      :show-empty-entries="false"
    />
  </SelectedItemSummary>
</template>

<script lang="ts" src="./SelectedItemSummarySelectorComponent.ts" />
<style scoped lang="css" src="./SelectedItemSummarySelectorComponent.css" />
<style lang="css" src="./SelectedItemSummarySelectorComponent.unscoped.css" />