<template>
  <SelectedItemSummary
    v-if="inventoryItem != null && selectedItem != null"
    :can-be-looted="canBeLooted"
    :inventory-item-in-same-slot-in-preset="inventoryItemInSameSlotInPreset"
    :inventory-item="inventoryItem"
  >
    <AmmunitionSummary
      v-if="isAmmunition"
      :item="selectedItem"
      :show-empty-entries="false"
    />
    <ArmorSummary
      v-else-if="isArmor"
      :armor-modifiers-override="selectedItemArmorModifiers"
      :item="selectedItem"
      :show-empty-entries="false"
    />
    <ArmorModSummary
      v-else-if="isArmorMod"
      :item="selectedItem"
      :show-empty-entries="false"
    />
    <BackpackSummary
      v-else-if="isBackpack"
      :item="selectedItem"
    />
    <ContainerSummary
      v-else-if="isContainer"
      :item="selectedItem"
    />
    <EyewearSummary
      v-else-if="isEyewear"
      :item="selectedItem"
      :show-empty-entries="false"
    />
    <GrenadeSummary
      v-else-if="isGrenade"
      :item="selectedItem"
      :show-empty-entries="false"
    />
    <HeadwearSummary
      v-else-if="isHeadwear"
      :item="selectedItem"
      :show-empty-entries="false"
    />
    <MagazineSummary
      v-else-if="isMagazine"
      :item="selectedItem"
      :show-empty-entries="false"
    />
    <MeleeWeaponSummary
      v-else-if="isMeleeWeapon"
      :item="selectedItem"
    />
    <ModSummary
      v-else-if="isMod"
      :item="selectedItem"
      :show-empty-entries="false"
    />
    <RangedWeaponSummary
      v-else-if="isRangedWeapon"
      :item="selectedItem"
    />
    <RangedWeaponModSummary
      v-else-if="isRangedWeaponMod"
      :item="selectedItem"
      :show-empty-entries="false"
    />
    <VestSummary
      v-else-if="isVest"
      :armor-modifiers-override="selectedItemArmorModifiers"
      :item="selectedItem"
      :show-empty-entries="false"
    />
  </SelectedItemSummary>
</template>

<script lang="ts" src="./SelectedItemSummarySelectorComponent.ts" />
<style scoped lang="css" src="./SelectedItemSummarySelectorComponent.css" />
<style lang="css" src="./SelectedItemSummarySelectorComponent.unscoped.css" />