<template>
  <SelectedItemSummary
    v-if="modelValue != null && item != null"
    v-model="modelValue"
    :can-be-looted="canBeLooted"
    :preset="preset"
  >
    <AmmunitionSummary
      v-if="isAmmunition"
      :item="item"
      :show-empty-entries="false"
    />
    <ArmorSummary
      v-else-if="isArmor"
      :armor-modifiers-override="armorModifiers"
      :item="item"
      :show-empty-entries="false"
    />
    <ArmorModSummary
      v-else-if="isArmorMod"
      :item="item"
      :show-empty-entries="false"
    />
    <BackpackSummary
      v-else-if="isBackpack"
      :item="item"
    />
    <ContainerSummary
      v-else-if="isContainer"
      :item="item"
    />
    <EyewearSummary
      v-else-if="isEyewear"
      :item="item"
      :show-empty-entries="false"
    />
    <GrenadeSummary
      v-else-if="isGrenade"
      :item="item"
      :show-empty-entries="false"
    />
    <HeadwearSummary
      v-else-if="isHeadwear"
      :item="item"
      :show-empty-entries="false"
    />
    <MagazineSummary
      v-else-if="isMagazine"
      :item="item"
      :show-empty-entries="false"
    />
    <MeleeWeaponSummary
      v-else-if="isMeleeWeapon"
      :item="item"
    />
    <ModSummary
      v-else-if="isMod"
      :item="item"
      :show-empty-entries="false"
    />
    <RangedWeaponSummary
      v-else-if="isRangedWeapon"
      :item="item"
    />
    <RangedWeaponModSummary
      v-else-if="isRangedWeaponMod"
      :item="item"
      :show-empty-entries="false"
    />
    <VestSummary
      v-else-if="isVest"
      :armor-modifiers-override="armorModifiers"
      :item="item"
      :show-empty-entries="false"
    />
  </SelectedItemSummary>
</template>

<script lang="ts" src="./SelectedItemSummarySelectorComponent.ts" />
<style scoped lang="css" src="./SelectedItemSummarySelectorComponent.css" />
<style lang="css" src="./SelectedItemSummarySelectorComponent.unscoped.css" />